# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiKey', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=10)),
                ('calls', models.IntegerField()),
                ('firstCall', models.DecimalField(decimal_places=3, max_digits=25)),
                ('lastCall', models.DecimalField(decimal_places=3, max_digits=25)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=25)),
                ('apiUrl', models.CharField(max_length=100)),
            ],
        ),
    ]
